apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-06-03T14:43:43Z
  generation: 1
  labels:
    run: upflvp
  name: {{ .Values.name.upflvp }}
  namespace: {{ .Values.namespace }}
  resourceVersion: "65465"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/upflvp
  uid: 8340cd2f-673c-11e8-9da6-0e5035f38654
spec:
  replicas: 1
  selector:
    matchLabels:
      run: upflvp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: upflvp
    spec:
      containers:
      - image: {{ .Values.image.upflvp.client }}
        imagePullPolicy: Always
        name: upflvpclient
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: {{ .Values.image.upflvp.server }}
        imagePullPolicy: Always
        name: upflvpserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-06-03T14:43:43Z
    lastUpdateTime: 2018-06-03T14:43:43Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
