apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-06-03T14:43:43Z
  generation: 1
  labels:
    run: mmwvrru
  name: mmwvrru
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mmwvrru
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mmwvrru
    spec:
      containers:
      - image: {{ .Values.image.mmwvrru.client }}
        imagePullPolicy: Always
        name: mmwvrruclient
        postStart:
        exec:
          command: ["/bin/sh", "-c", "sleep 10"]
        env:
        - name: PY_SERVER
          value: {{ .Values.connection.mmwvrru }}
        resources: {}
      - image: {{ .Values.image.mmwvrru.server }}
        imagePullPolicy: Always
        name: mmwvrruserver
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
